// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'default_values_lib.dart' as prefix1;
import 'default_values_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.MyReflectable(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"A",
            r"test_reflectable.test.default_values_test.A",
            7,
            0,
            const prefix0.MyReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r"optional": (b) => (
                      [x = prefix1.A.localConstant + 31,
                      y = identical(
                          prefix0.globalConstant, prefix0.globalConstant),
                      z = prefix1.globalConstant + prefix1.globalConstant,
                      w = const [
                        String,
                        null,
                        prefix0.myReflectable,
                        const prefix0.B(named: 24),
                        const <int, Type>{1: prefix0.A}
                      ]]) =>
                  b ? new prefix0.A.optional(x, y, z, w) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {})
      ],
      null,
      null,
      <Type>[prefix0.A],
      1,
      {},
      {},
      null,
      [
        const [4, 4, null]
      ])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
