// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'inherited_variable_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"C",
            r"test_reflectable.test.inherited_variable_test.C",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[],
            const <int>[1, 2, 3, 4, 5, 6, 7],
            const <int>[],
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(
            r"x", 32773, null, const prefix0.Reflector(), -1, -1, -1, null),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, const <int>[0],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1,
            const <int>[1], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), null),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, -1, -1, 6),
        new r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, -1, -1, 7)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"other", 16390, 1, const prefix0.Reflector(),
            null, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 3,
            const prefix0.Reflector(), -1, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"_x", 32870, 7, const prefix0.Reflector(),
            -1, -1, -1, null, null, null)
      ],
      <Type>[prefix0.C],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"x": (dynamic instance) => instance.x
      },
      {r"x=": (dynamic instance, value) => instance.x = value},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
