// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'literal_type_arguments_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"C",
            r"test_reflectable.test.literal_type_arguments_test.C",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1],
            const <int>[2, 3, 4, 5, 6, 0, 1],
            const <int>[],
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        new r.MethodMirrorImpl(
            r"foo",
            131075,
            0,
            -1,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[
              const prefix0.ListMetadata(const <int>[1, 2])
            ]),
        new r.MethodMirrorImpl(
            r"bar",
            131075,
            0,
            -1,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[
              const prefix0.MapMetadata(
                  const <int, prefix0.Reflector>{3: prefix0.reflector})
            ]),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, const <int>[0],
            const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1,
            const <int>[1], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), const <Object>[])
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"other", 16390, 2, const prefix0.Reflector(),
            null, -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 4,
            const prefix0.Reflector(), -1, -1, -1, const <Object>[], null, null)
      ],
      <Type>[prefix0.C],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"foo": (dynamic instance) => instance.foo,
        r"bar": (dynamic instance) => instance.bar
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
