// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'member_capability_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.MyReflectable(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"Foo",
            r"test_reflectable.test.member_capability_test.Foo",
            7,
            0,
            const prefix0.MyReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix0.Foo() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"x": 0,
              r"y": 1,
              r"a": 0,
              r"a=": 1,
              r"b": 0,
              r"b=": 1
            })
      ],
      null,
      null,
      <Type>[prefix0.Foo],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"x": (dynamic instance) => instance.x,
        r"y": (dynamic instance) => instance.y,
        r"a": (dynamic instance) => instance.a,
        r"b": (dynamic instance) => instance.b
      },
      {
        r"a=": (dynamic instance, value) => instance.a = value,
        r"b=": (dynamic instance, value) => instance.b = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null]
      ]),
  const prefix0.MyReflectable2(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"Foo2",
            r"test_reflectable.test.member_capability_test.Foo2",
            7,
            0,
            const prefix0.MyReflectable2(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            {r"x": 0, r"b": 0, r"b=": 1})
      ],
      null,
      null,
      <Type>[prefix0.Foo2],
      1,
      {
        r"x": (dynamic instance) => instance.x,
        r"b": (dynamic instance) => instance.b
      },
      {r"b=": (dynamic instance, value) => instance.b = value},
      null,
      [
        const [0, 0, null],
        const [1, 0, null]
      ]),
  const prefix0.MyReflectable3(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"Foo3",
            r"test_reflectable.test.member_capability_test.Foo3",
            7,
            0,
            const prefix0.MyReflectable3(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            {r"c": 1, r"c=": 0, r"y": 0, r"b": 1, r"b=": 0})
      ],
      null,
      null,
      <Type>[prefix0.Foo3],
      1,
      {
        r"c": (dynamic instance) => instance.c,
        r"y": (dynamic instance) => instance.y,
        r"b": (dynamic instance) => instance.b
      },
      {
        r"c=": (dynamic instance, value) => instance.c = value,
        r"b=": (dynamic instance, value) => instance.b = value
      },
      null,
      [
        const [1, 0, null],
        const [0, 0, null]
      ])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
