// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'mixin_static_const_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"M",
            r"test_reflectable.test.mixin_static_const_test.M",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 2],
            const <int>[3, 4, 5, 6, 7],
            const <int>[1],
            -1,
            {r"s": () => prefix0.M.s},
            {},
            {r"": (b) => () => b ? new prefix0.M() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        new r.NonGenericClassMirrorImpl(
            r"B",
            r"test_reflectable.test.mixin_static_const_test.B",
            7,
            1,
            const prefix0.Reflector(),
            const <int>[8],
            const <int>[3, 4, 5, 6, 7],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix0.B() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        new r.NonGenericClassMirrorImpl(
            r"test_reflectable.test.mixin_static_const_test.A with test_reflectable.test.mixin_static_const_test.M",
            r"test_reflectable.test.mixin_static_const_test.test_reflectable.test.mixin_static_const_test.A with test_reflectable.test.mixin_static_const_test.M",
            583,
            2,
            const prefix0.Reflector(),
            const <int>[],
            const <int>[3, 4, 5, 6, 7],
            const <int>[],
            -1,
            const {},
            const {},
            const {},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(
            r"s", 33941, 0, const prefix0.Reflector(), -1, -1, -1, null),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, -1, -1, 1),
        new r.MethodMirrorImpl(r"", 64, 0, -1, -1, -1, const <int>[],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, const <int>[0],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1,
            const <int>[1], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"", 64, 1, -1, -1, -1, const <int>[],
            const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"other", 16390, 3, const prefix0.Reflector(),
            null, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 5,
            const prefix0.Reflector(), -1, -1, -1, null, null, null)
      ],
      <Type>[
        prefix0.M,
        prefix0.B,
        const r.FakeType(
            r"test_reflectable.test.mixin_static_const_test.test_reflectable.test.mixin_static_const_test.A with test_reflectable.test.mixin_static_const_test.M")
      ],
      3,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
