// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'parameter_mirrors_lib.dart' as prefix1;
import 'parameter_mirrors_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"A",
            r"test_reflectable.test.parameter_mirrors_test.A",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3],
            const <int>[4, 5, 6, 7, 8, 0, 1, 2, 3],
            const <int>[],
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[const prefix0.Reflector()],
            null)
      ],
      <m.DeclarationMirror>[
        new r.MethodMirrorImpl(r"f1", 65538, 0, null, -1, -1, const <int>[],
            const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"f2", 65538, 0, null, -1, -1, const <int>[0],
            const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"f3", 65538, 0, null, -1, -1,
            const <int>[1, 2, 3], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"f4", 65538, 0, null, -1, -1,
            const <int>[4, 5, 6], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, const <int>[7],
            const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1,
            const <int>[8], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), const <Object>[]),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Reflector(), const <Object>[])
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"a", 32774, 1, const prefix0.Reflector(), -1,
            -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"a", 32774, 2, const prefix0.Reflector(), -1,
            -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"b", 36870, 2, const prefix0.Reflector(), -1,
            -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"c", 38918, 2, const prefix0.Reflector(), -1,
            -1, -1, const <Object>[const prefix0.C()], "ten", null),
        new r.ParameterMirrorImpl(r"a", 32774, 3, const prefix0.Reflector(), -1,
            -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"b", 45062, 3, const prefix0.Reflector(), 0,
            -1, -1, const <Object>[const prefix1.D(3)], null, #b),
        new r.ParameterMirrorImpl(r"c", 47110, 3, const prefix0.Reflector(), -1,
            -1, -1, const <Object>[], const prefix0.C(), #c),
        new r.ParameterMirrorImpl(r"other", 16390, 4, const prefix0.Reflector(),
            null, -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 6,
            const prefix0.Reflector(), -1, -1, -1, const <Object>[], null, null)
      ],
      <Type>[prefix0.A],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"f1": (dynamic instance) => instance.f1,
        r"f2": (dynamic instance) => instance.f2,
        r"f3": (dynamic instance) => instance.f3,
        r"f4": (dynamic instance) => instance.f4
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
