// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'reflected_type_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"A",
            r"test_reflectable.test.reflected_type_test.A",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            const <int>[16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 11, 12],
            const <int>[7, 8, 9, 10, 13, 14],
            -1,
            {
              r"noArguments": () => prefix0.A.noArguments,
              r"oneArgument": () => prefix0.A.oneArgument,
              r"optionalArguments": () => prefix0.A.optionalArguments,
              r"namedArguments": () => prefix0.A.namedArguments,
              r"staticGetset": () => prefix0.A.staticGetset
            },
            {r"staticGetset=": (value) => prefix0.A.staticGetset = value},
            {r"": (b) => () => b ? new prefix0.A() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.MethodMirrorImpl(r"arg0", 131074, 0, -1, 1, 1, const <int>[],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"arg1", 131074, 0, -1, 1, 1, const <int>[0],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"arg2to4", 131074, 0, -1, 1, 1,
            const <int>[1, 2, 3, 4], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"argNamed", 131074, 0, -1, 1, 1,
            const <int>[5, 6, 7], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"+", 131074, 0, -1, 1, 1, const <int>[8],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"[]", 131074, 0, -1, 1, 1, const <int>[9],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"[]=", 262146, 0, null, -1, -1,
            const <int>[10, 11], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"noArguments", 131090, 0, -1, 1, 1,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"oneArgument", 131090, 0, -1, 1, 1,
            const <int>[12], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"optionalArguments", 131090, 0, -1, 1, 1,
            const <int>[13, 14, 15, 16], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"namedArguments", 131090, 0, -1, 1, 1,
            const <int>[17, 18, 19], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"getset", 131075, 0, -1, 2, 2, const <int>[],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"getset=", 262148, 0, null, -1, -1,
            const <int>[20], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"staticGetset", 4325395, 0, -1, 3, 4,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"staticGetset=", 262164, 0, null, -1, -1,
            const <int>[21], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"", 64, 0, -1, 0, 0, const <int>[],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, 5, 5, const <int>[22],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, 2, 2,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, null, null,
            const <int>[23], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, 1, 1,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, 6, 6,
            const <int>[], const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"x", 32774, 1, const prefix0.Reflector(), -1,
            1, 1, null, null, null),
        new r.ParameterMirrorImpl(r"x", 32774, 2, const prefix0.Reflector(), 0,
            0, 0, null, null, null),
        new r.ParameterMirrorImpl(r"y", 32774, 2, const prefix0.Reflector(), -1,
            1, 1, null, null, null),
        new r.ParameterMirrorImpl(r"z", 36870, 2, const prefix0.Reflector(), -1,
            7, 7, null, null, null),
        new r.ParameterMirrorImpl(r"w", 22534, 2, const prefix0.Reflector(),
            null, null, null, null, 41.99999999, null),
        new r.ParameterMirrorImpl(r"x", 32774, 3, const prefix0.Reflector(), -1,
            1, 1, null, null, null),
        new r.ParameterMirrorImpl(r"y", 16390, 3, const prefix0.Reflector(),
            null, null, null, null, null, null),
        new r.ParameterMirrorImpl(r"z", 45062, 3, const prefix0.Reflector(), -1,
            8, 8, null, null, #z),
        new r.ParameterMirrorImpl(r"x", 32774, 4, const prefix0.Reflector(), -1,
            1, 1, null, null, null),
        new r.ParameterMirrorImpl(r"x", 32774, 5, const prefix0.Reflector(), -1,
            1, 1, null, null, null),
        new r.ParameterMirrorImpl(r"x", 32774, 6, const prefix0.Reflector(), -1,
            1, 1, null, null, null),
        new r.ParameterMirrorImpl(r"v", 16390, 6, const prefix0.Reflector(),
            null, null, null, null, null, null),
        new r.ParameterMirrorImpl(r"x", 32774, 8, const prefix0.Reflector(), -1,
            2, 2, null, null, null),
        new r.ParameterMirrorImpl(r"x", 32774, 9, const prefix0.Reflector(), 0,
            0, 0, null, null, null),
        new r.ParameterMirrorImpl(r"y", 32774, 9, const prefix0.Reflector(), -1,
            9, 9, null, null, null),
        new r.ParameterMirrorImpl(r"z", 36870, 9, const prefix0.Reflector(), -1,
            7, 7, null, null, null),
        new r.ParameterMirrorImpl(r"w", 22534, 9, const prefix0.Reflector(),
            null, null, null, null, 42, null),
        new r.ParameterMirrorImpl(r"x", 32774, 10, const prefix0.Reflector(),
            -1, 2, 2, null, null, null),
        new r.ParameterMirrorImpl(r"y", 2129926, 10, const prefix0.Reflector(),
            -1, 10, 11, null, null, null),
        new r.ParameterMirrorImpl(r"z", 47110, 10, const prefix0.Reflector(),
            -1, 2, 2, null, "4" + "2", #z),
        new r.ParameterMirrorImpl(r"string", 32774, 12,
            const prefix0.Reflector(), -1, 2, 2, null, null, null),
        new r.ParameterMirrorImpl(r"list", 2129926, 14,
            const prefix0.Reflector(), -1, 3, 4, null, null, null),
        new r.ParameterMirrorImpl(r"other", 16390, 16,
            const prefix0.Reflector(), null, null, null, null, null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 18,
            const prefix0.Reflector(), -1, 12, 12, null, null, null)
      ],
      <Type>[
        prefix0.A,
        int,
        String,
        const m.TypeValue<List<String>>().type,
        List,
        bool,
        Type,
        prefix0.Reflector,
        num,
        double,
        const m.TypeValue<List<dynamic>>().type,
        List,
        Invocation
      ],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"arg0": (dynamic instance) => instance.arg0,
        r"arg1": (dynamic instance) => instance.arg1,
        r"arg2to4": (dynamic instance) => instance.arg2to4,
        r"argNamed": (dynamic instance) => instance.argNamed,
        r"+": (dynamic instance) => (x) => instance + x,
        r"[]": (dynamic instance) => (x) => instance[x],
        r"[]=": (dynamic instance) => (x, v) => instance[x] = v,
        r"getset": (dynamic instance) => instance.getset
      },
      {r"getset=": (dynamic instance, value) => instance.getset = value},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
