// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'package:test_reflectable/serialize.dart' as prefix0;
import 'serialize_test.dart' as prefix1;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Serializable(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"A",
            r"test_reflectable.test.serialize_test.A",
            7,
            0,
            const prefix0.Serializable(),
            const <int>[0, 1, 3, 4, 9],
            const <int>[4, 3, 10, 11, 12, 5, 6, 7, 8],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix1.A() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        new r.NonGenericClassMirrorImpl(
            r"B",
            r"test_reflectable.test.serialize_test.B",
            7,
            1,
            const prefix0.Serializable(),
            const <int>[2, 13, 16],
            const <int>[13, 3, 10, 11, 12, 5, 6, 7, 8, 14, 15],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix1.B() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(
            r"a", 16389, 0, const prefix0.Serializable(), null, -1, -1, null),
        new r.VariableMirrorImpl(
            r"b", 16389, 0, const prefix0.Serializable(), null, -1, -1, null),
        new r.VariableMirrorImpl(
            r"c", 16389, 1, const prefix0.Serializable(), null, -1, -1, null),
        new r.MethodMirrorImpl(r"toString", 65538, 0, null, -1, -1,
            const <int>[], const prefix0.Serializable(), null),
        new r.MethodMirrorImpl(r"==", 131074, 0, -1, -1, -1, const <int>[0],
            const prefix0.Serializable(), null),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Serializable(), 0, -1, -1, 5),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Serializable(), 0, -1, -1, 6),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Serializable(), 1, -1, -1, 7),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Serializable(), 1, -1, -1, 8),
        new r.MethodMirrorImpl(r"", 0, 0, -1, -1, -1, const <int>[],
            const prefix0.Serializable(), null),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1,
            const <int>[3], const prefix0.Serializable(), null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Serializable(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1,
            const <int>[], const prefix0.Serializable(), null),
        new r.MethodMirrorImpl(r"==", 131074, 1, -1, -1, -1, const <int>[4],
            const prefix0.Serializable(), null),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Serializable(), 2, -1, -1, 14),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Serializable(), 2, -1, -1, 15),
        new r.MethodMirrorImpl(r"", 0, 1, -1, -1, -1, const <int>[],
            const prefix0.Serializable(), null)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"other", 16390, 4,
            const prefix0.Serializable(), null, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"_a", 16486, 6, const prefix0.Serializable(),
            null, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"_b", 16486, 8, const prefix0.Serializable(),
            null, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 10,
            const prefix0.Serializable(), -1, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"other", 16390, 13,
            const prefix0.Serializable(), null, -1, -1, null, null, null),
        new r.ParameterMirrorImpl(r"_c", 16486, 15,
            const prefix0.Serializable(), null, -1, -1, null, null, null)
      ],
      <Type>[prefix1.A, prefix1.B],
      2,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"a": (dynamic instance) => instance.a,
        r"b": (dynamic instance) => instance.b,
        r"c": (dynamic instance) => instance.c
      },
      {
        r"a=": (dynamic instance, value) => instance.a = value,
        r"b=": (dynamic instance, value) => instance.b = value,
        r"c=": (dynamic instance, value) => instance.c = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
