// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'static_members_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.MyReflectable(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"A",
            r"test_reflectable.test.static_members_test.A",
            7,
            0,
            const prefix0.MyReflectable(),
            const <int>[0],
            const <int>[],
            const <int>[1],
            -1,
            {r"foo": () => prefix0.A.foo},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(r"foo", 2131093, 0,
            const prefix0.MyReflectable(), -1, -1, -1, null),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.MyReflectable(), 0, -1, -1, 1)
      ],
      <m.ParameterMirror>[],
      <Type>[prefix0.A],
      1,
      {},
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
