// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'subtype_quantify_test.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"A",
            r"test_reflectable.test.subtype_quantify_test.A",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {},
            -1,
            0,
            const <int>[],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"foo": 0
            }),
        new r.NonGenericClassMirrorImpl(
            r"B",
            r"test_reflectable.test.subtype_quantify_test.B",
            7,
            1,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            0,
            {},
            {},
            {},
            -1,
            1,
            const <int>[],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"foo": 0
            }),
        new r.NonGenericClassMirrorImpl(
            r"C",
            r"test_reflectable.test.subtype_quantify_test.C",
            7,
            2,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {},
            -1,
            2,
            const <int>[0],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"foo": 0
            }),
        new r.NonGenericClassMirrorImpl(
            r"D",
            r"test_reflectable.test.subtype_quantify_test.D",
            7,
            3,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            2,
            const {},
            const {},
            const {},
            -1,
            -1,
            const <int>[],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"foo": 0
            }),
        new r.NonGenericClassMirrorImpl(
            r"test_reflectable.test.subtype_quantify_test.C with test_reflectable.test.subtype_quantify_test.M",
            r"test_reflectable.test.subtype_quantify_test.test_reflectable.test.subtype_quantify_test.C with test_reflectable.test.subtype_quantify_test.M",
            583,
            4,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            2,
            const {},
            const {},
            const {},
            -1,
            -1,
            const <int>[],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"foo": 0
            }),
        new r.NonGenericClassMirrorImpl(
            r"D",
            r"test_reflectable.test.subtype_quantify_test.D",
            7,
            5,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            3,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"foo": 0
            }),
        new r.NonGenericClassMirrorImpl(
            r"E",
            r"test_reflectable.test.subtype_quantify_test.E",
            7,
            6,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            4,
            {},
            {},
            {},
            -1,
            6,
            const <int>[],
            null,
            {
              r"==": 1,
              r"toString": 0,
              r"noSuchMethod": 1,
              r"hashCode": 0,
              r"runtimeType": 0,
              r"foo": 0
            })
      ],
      null,
      null,
      <Type>[
        prefix0.A,
        prefix0.B,
        prefix0.C,
        prefix0.D,
        const r.FakeType(
            r"test_reflectable.test.subtype_quantify_test.test_reflectable.test.subtype_quantify_test.C with test_reflectable.test.subtype_quantify_test.M"),
        prefix0.D,
        prefix0.E
      ],
      7,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"foo": (dynamic instance) => instance.foo
      },
      {},
      null,
      [
        const [0, 0, null],
        const [1, 0, null]
      ])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
